# -*- coding: utf-8 -*-
"""Tarea_02  Aliste Catalina

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GRgjttBu_rjzPx6D5qEN6zqCqeNARXZ8
"""

for x in range(100):
  print(x+1)

for x in range(100):

  if (x+1) % 3 == 0:
    print(x+1)

numero_1 = int(input("Ingresa un número"))
numero_2 = 5
suma = numero_1 + numero_2
resultado = ""

if(suma<100):
  resultado = "menor a 100"
elif(suma>100 and suma<150):
    resultado = "mayor a 100"
elif(suma>=150):
    resultado = "mayor a 150"

print(resultado)

edad = int(input("indica tu edad"))
programar = input("¿te gusta programar?(si o no)")
if int(edad>18 and programar == "si"):
  print("eres mayor de edad y te gusta programar")

if int(edad>18 and programar == "no"):
    print("eres mayor de edad y no te gusta programar")

if int(edad<18 and programar == "si"):
    print("eres menor de edad y te gusta programar")

if int(edad<18 and programar == "no"):
    print("eres menor de edad y no te gusta programar")